export function foo(): void {
  throw new Error("Throw from catch");
}